spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect