spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/notes
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
            database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true